version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "ok-to-test"
      - "release-note-none"
    open-pull-requests-limit: 10
    groups:
      all:
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for kjobctl
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/hack/tools"
    schedule:
      interval: "weekly"
    labels:
      - "ok-to-test"
      - "release-note-none"
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
    ignore:
      # Ignore major and minor versions for dependencies updates
      # Allow patches and security updates.
      - dependency-name: k8s.io/*
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "docker"
    directory: "/hack/shellcheck"
    schedule:
      interval: "weekly"
    labels:
      - "ok-to-test"
      - "release-note-none"
