kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiVersion: kubeadm.k8s.io/v1beta3
        scheduler:
          extraArgs:
            v: "3"
        controllerManager:
          extraArgs:
            v: "3"
        apiServer:
          extraArgs:
            enable-aggregator-routing: "true"
            v: "3"
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            v: "3"
  - role: worker
    labels:
      cloud.google.com/gke-node-group: tas-group
      cloud.google.com/gke-tpu-accelerator: tpu7x
      cloud.google.com/gce-topology-block: b1
      cloud.google.com/gke-tpu-partition-4x4x4-id: sb1
      cloud.google.com/gke-tpu-partition-4x4x4-state: HEALTHY
  - role: worker
    labels:
      cloud.google.com/gke-node-group: tas-group
      cloud.google.com/gke-tpu-accelerator: tpu7x
      cloud.google.com/gce-topology-block: b2
      cloud.google.com/gke-tpu-partition-4x4x4-id: sb2
      cloud.google.com/gke-tpu-partition-4x4x4-state: HEALTHY
  - role: worker
    labels:
      cloud.google.com/gke-node-group: tas-group
      cloud.google.com/gke-tpu-accelerator: tpu7x
      cloud.google.com/gce-topology-block: b2
      cloud.google.com/gke-tpu-partition-4x4x4-id: sb3
      cloud.google.com/gke-tpu-partition-4x4x4-state: HEALTHY
  - role: worker
    labels:
      cloud.google.com/gke-node-group: tas-group
      cloud.google.com/gke-tpu-accelerator: tpu7x
      cloud.google.com/gce-topology-block: b2
      cloud.google.com/gke-tpu-partition-4x4x4-id: sb4
      cloud.google.com/gke-tpu-partition-4x4x4-state: HEALTHY
kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "3"
