kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiVersion: kubeadm.k8s.io/v1beta3
        scheduler:
          extraArgs:
            v: "3"
        controllerManager:
          extraArgs:
            v: "3"
        apiServer:
          extraArgs:
            enable-aggregator-routing: "true"
            v: "3"
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            v: "3"
  - role: worker
    labels:
      instance-type: on-demand
      cloud.google.com/gke-tpu-topology: 2x2x2
      cloud.google.com/gke-tpu-accelerator: tpu-v4-podslice
      cloud.google.com/gke-tpu-reservation-subblock: tpu-subblock-1
  - role: worker
    labels:
      instance-type: on-demand
      cloud.google.com/gke-tpu-topology: 2x2x2
      cloud.google.com/gke-tpu-accelerator: tpu-v4-podslice
      cloud.google.com/gke-nodepool: tpu-v4-pool
kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "3"
