apiVersion: v1
kind: PersistentVolume
metadata:
  name: xpk-lustre-pv
spec:
  storageClassName: ""
  capacity:
    storage: STORAGE_SIZE #ex. 36000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: default
    name: xpk-lustre-pvc
  csi:
    driver: lustre.csi.storage.gke.io
    volumeHandle: "PROJECT_ID/ZONE/INSTANCE_NAME"
    volumeAttributes:
      ip: IP_ADDRESS
      filesystem: FILE_SYSTEM
---
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: xpk-lustre-pvc
  spec:
    accessModes:
      - ReadWriteMany
    storageClassName: ""
    volumeName: xpk-lustre-pv
    resources:
      requests:
        storage: STORAGE_SIZE
