apiVersion: v1
kind: PersistentVolume
metadata:
  name: xpk-parallelstore-pv
spec:
  storageClassName: xpk-parallelstore-class
  capacity:
    storage: STORAGE_SIZE #ex: 12000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: parallelstore.csi.storage.gke.io
    volumeHandle: "PROJECT_ID/ZONE/INSTANCE_NAME/default-pool/default-container"
    volumeAttributes:
      accessPoints: IP_ADDRESSES #comma separated
      network: projects/PROJECT_ID/global/networks/NETWORK_NAME #VPC Network
  claimRef:
    name: xpk-parallelstore-pvc
    namespace: default
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: xpk-parallelstore-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: xpk-parallelstore-class
  resources:
    requests:
      storage: STORAGE_SIZE #ex: 12000Gi