"""
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

# This file is generated by tools/update_dependencies.py. DO NOT EDIT.
import dataclasses
import enum


@dataclasses.dataclass(frozen=True)
class BinaryDependency:
  """Represents a binary dependency with its metadata and checksums."""

  archive_type: str
  binary_name: str
  checksums: dict[str, str]
  url_template: str
  version: str
  arch_map: dict[str, str] = dataclasses.field(default_factory=dict)
  os_map: dict[str, str] = dataclasses.field(default_factory=dict)


class BinaryDependencies(enum.Enum):
  """Enum of binary dependencies with their metadata and checksums."""

  KUBECTL = BinaryDependency(
      archive_type='binary',
      binary_name='kubectl',
      checksums={
          'darwin_amd64': (
              '163955964d4ed9e66656eab45c0114f5c1110d1b430ace432b20ddc430023df5'
          ),
          'darwin_arm64': (
              'b0b59cdd7ba20ca20b85214943100e578dd50ddd85242fcddf277a87c2249706'
          ),
          'linux_amd64': (
              '924eb50779153f20cb668117d141440b95df2f325a64452d78dff9469145e277'
          ),
          'linux_arm64': (
              'cd859449f54ad2cb05b491c490c13bb836cdd0886ae013c0aed3dd67ff747467'
          ),
      },
      url_template=(
          'https://dl.k8s.io/release/{version}/bin/{os}/{arch}/kubectl'
      ),
      version='v1.35.2',
  )
  KUBECTL_KUEUE = BinaryDependency(
      archive_type='binary',
      binary_name='kubectl-kueue',
      checksums={
          'darwin_amd64': (
              'a10092043ae4d78263543f3f5a6ffd694755ebe573213ba368aa72e1f9c51dd1'
          ),
          'darwin_arm64': (
              'b10ccad6f3c1b082dc16215b58717cd1c6ecaaf395212031e8305657a7348819'
          ),
          'linux_amd64': (
              '1c4b17581369b317d04a02dcd23e73b5a4644e6c2fc19ecd550b1e5aedb119bb'
          ),
          'linux_arm64': (
              '1ad79a020f9fe350a3e045fd06aaba77f949d0a9c70c8a0165557f8d53e78c1d'
          ),
      },
      url_template='https://github.com/kubernetes-sigs/kueue/releases/download/{version}/kubectl-kueue-{os}-{arch}',
      version='v0.17.1',
  )
  CRANE = BinaryDependency(
      archive_type='tar.gz',
      binary_name='crane',
      checksums={
          'darwin_amd64': (
              '4f9ee5012e767f510abd9a31abb7da0de36fa07494e6a310c7b667dc40a5e108'
          ),
          'darwin_arm64': (
              'd3ee7088bec79c7950efae4c9496efbc64d6bb9d393a882e0d9d38a7d1dd4a11'
          ),
          'linux_amd64': (
              '897e7c342db072ba76531246fc18fbf3e8e298688b6ecf98916770984b263866'
          ),
          'linux_arm64': (
              '162c602f2ae4c4b15c36a08eaf501d301493fb128ca32443611107a1b26868fa'
          ),
      },
      url_template='https://github.com/google/go-containerregistry/releases/download/{version}/go-containerregistry_{os}_{arch}.tar.gz',
      version='v0.21.2',
      arch_map={'amd64': 'x86_64', 'arm64': 'arm64'},
      os_map={'darwin': 'Darwin', 'linux': 'Linux'},
  )
  GCLUSTER = BinaryDependency(
      archive_type='zip',
      binary_name='gcluster',
      checksums={
          'darwin_amd64': (
              'e755236cc45cf15bf277e6c15c212fccc426580f3d0ac8f95f27302cd03c3456'
          ),
          'darwin_arm64': (
              'b18a586cb895cd824b8e041fb1f0d87bd2f250304c89cb4e16e4024d1942e3e3'
          ),
          'linux_amd64': (
              '4010577ced2f54a23482eebf5f269e855d5ef5584a34959859eda0788430cf03'
          ),
          'linux_arm64': (
              '4e7332759af90dc0d9d65164cf1311fea0f8c382fcaff130910ff27023e50e8e'
          ),
      },
      url_template='https://github.com/GoogleCloudPlatform/cluster-toolkit/releases/download/{version}/gcluster_bundle_{os}_{arch}.zip',
      version='v1.94.0',
      os_map={'darwin': 'mac'},
  )
