"""
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

# This file is generated by tools/update_dependencies.py. DO NOT EDIT.
from typing import Any

DEPENDENCIES: dict[str, dict[str, Any]] = {
    'crane': {
        'archive_type': 'tar.gz',
        'binary_name': 'crane',
        'checksums': {
            'darwin_amd64': '69af8da281cd2cd56245bf178de8719bbcdd2ffdeae46b4c621c02bfc6f75e22',
            'darwin_arm64': '210da17a7269a9904a9b6797efbf97f4b1e5567c0962f168d1489a7bd375f14a',
            'linux_amd64': '8ef3564d264e6b5ca93f7b7f5652704c4dd29d33935aff6947dd5adefd05953e',
            'linux_arm64': 'b04ee6e4904d9219c76383f5b73521a63f69ecc93c0b1840846eebfd071a6355',
        },
        'url_template': 'https://github.com/google/go-containerregistry/releases/download/{version}/go-containerregistry_{os_capitalized}_{crane_arch}.tar.gz',
        'version': 'v0.20.7',
    },
    'kubectl': {
        'archive_type': 'binary',
        'binary_name': 'kubectl',
        'checksums': {
            'darwin_amd64': 'bcfa57d020b8d07d0ea77235ce8012c2c28fefdfd7cb9738f33674a7b16cef08',
            'darwin_arm64': '45cfa208151320153742062824398f22bb6bfb5a142bf6238476d55dacbd1bdd',
            'linux_amd64': '7c3807c0f5c1b30110a2ff1e55da1d112a6d0096201f1beb81b269f582b5d1c5',
            'linux_arm64': '669af0cf520757298ea60a8b6eb6b719ba443a9c7d35f36d3fb2fd7513e8c7d2',
        },
        'url_template': (
            'https://dl.k8s.io/release/{version}/bin/{os}/{arch}/kubectl'
        ),
        'version': 'v1.30.0',
    },
    'kubectl-kueue': {
        'archive_type': 'binary',
        'binary_name': 'kubectl-kueue',
        'checksums': {
            'darwin_amd64': 'a18199cfde78236c4a79dd5ab4f3f64be7491869430c90e536df58af5f893b9a',
            'darwin_arm64': 'b0d55bc9fa99feab049432b3c6dccac1e765c53b120825f3eb071476f361a4ff',
            'linux_amd64': 'c23438cbd52929a28013182496fc37bfb881921fb4e01c47476afb67b1021815',
            'linux_arm64': '2819f646ee2b55775f39bf3aaea3b7403cb15cbdf125812121da8b0c40bccb2a',
        },
        'url_template': 'https://github.com/kubernetes-sigs/kueue/releases/download/{version}/kubectl-kueue-{os}-{arch}',
        'version': 'v0.15.2',
    },
}
