# This patch adds the args to allow exposing the metrics endpoint using HTTPS
- op: add
  path: /spec/template/spec/containers/0/args/0
  value: --zap-devel
- op: add
  path: /spec/template/spec/containers/0/args/0
  value: --zap-log-level=3
