apiVersion: v1
kind: Service
metadata:
  name: slice-controller-webhook-service
  namespace: slice-controller-system
  labels:
    {{- include "slice.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/name: {{ include "slice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}