{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slice.serviceAccountName" . }}
  labels:
    {{- include "slice.labels" . | nindent 4 }}
{{- end -}}
