
apiVersion: v1
kind: PersistentVolume
metadata:
  name: xpk-filestore-pv
spec:
  storageClassName:
  capacity:
    storage: 
  accessModes:
  persistentVolumeReclaimPolicy: 
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle:
    volumeAttributes:
      ip:
      volume:
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: 
spec:
  accessModes:
  storageClassName:
  volumeName: 
  resources:
    requests:
      storage: 
