apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage:
  volumeName:
  storageClassName: example-storage-class