apiVersion: v1
kind: PersistentVolume
metadata:
  name:
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage:
  storageClassName: example-storage-class
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle:
    volumeAttributes:
      gcsfuseLoggingSeverity: warning