apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storages.xpk.x-k8s.io
spec:
  group: xpk.x-k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                cluster:
                  type: string
                auto_mount:
                  type: boolean
                mount_point:
                  type: string
                readonly:
                  type: boolean
                manifest:
                  type: string
                pv:
                  type: string
                pvc:
                  type: string
              required:
                - type
                - cluster
                - auto_mount
                - mount_point
                - readonly
                - manifest
                - pvc
                - pv
          x-kubernetes-validations:
            - message: Value is immutable
              rule: self == oldSelf
  scope: Cluster
  names:
    plural: storages
    singular: storage
    kind: Storage
    shortNames:
      - stg