apiVersion: v1
kind: PersistentVolume
metadata:
  name: xpk-filestore-pv
spec:
  storageClassName: "xpkdefsc"
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "projects/cloud-tpu-multipod-dev/locations/us-central1-c/instances/nfs-server/volumes/vol1"
    volumeAttributes:
      ip: 10.219.220.226
      volume: vol1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: podpvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "xpkdefsc"
  volumeName: xpk-filestore-pv
  resources:
    requests:
      storage: 1Ti

# python3 xpk.py storage create storage-attach --project=$PROJECT --cluster=ppawl-v4-xpk-test-tpu-1 --type=gcpfilestore --auto-mount=false --mount-point='/test-mount-point' --readonly=false --manifest='examples/filestore/attach-existing-fs-manifest.yaml' --zone us-central2