/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package slices

// Map creates a new slice with the same number elements as the input s with
// the values generated by mapFunc
func Map[From any, To any, S ~[]From](s S, mapFunc func(*From) To) []To {
	if s == nil {
		return nil
	}
	ret := make([]To, len(s))
	for i := range s {
		ret[i] = mapFunc(&s[i])
	}
	return ret
}
