# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.24.1-alpine

# Install necessary tools and libraries
RUN apk add git make bash

ARG KJOB_BRANCH=main
ARG KJOB_COMMIT_HASH=e2c92af44c047016cd5789995f6276b79f22663d

# Clone the kjob repository
RUN git clone --branch ${KJOB_BRANCH} --single-branch https://github.com/kubernetes-sigs/kjob.git /kjob

WORKDIR /kjob

# Checkout to stable commit
RUN git checkout ${KJOB_COMMIT_HASH}

# Build the kubectl-kjob binary
RUN make kubectl-kjob

