#!/usr/bin/env python3

"""
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import urllib.request
import hashlib
import pprint
import subprocess
from pathlib import Path
from typing import Any
from itertools import product

_KUBECTL_VERSION: str = "v1.30.0"
_KUEUE_VERSION: str = "v0.15.2"
_CRANE_VERSION: str = "v0.20.7"

_COPYRIGHT_STRING = """
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

_DEPENDENCIES: dict[str, dict[str, str]] = {
    "kubectl": {
        "version": _KUBECTL_VERSION,
        "url_template": (
            "https://dl.k8s.io/release/{version}/bin/{os}/{arch}/kubectl"
        ),
        "archive_type": "binary",
        "binary_name": "kubectl",
    },
    "kubectl-kueue": {
        "version": _KUEUE_VERSION,
        "url_template": "https://github.com/kubernetes-sigs/kueue/releases/download/{version}/kubectl-kueue-{os}-{arch}",
        "archive_type": "binary",
        "binary_name": "kubectl-kueue",
    },
    "crane": {
        "version": _CRANE_VERSION,
        "url_template": "https://github.com/google/go-containerregistry/releases/download/{version}/go-containerregistry_{os_capitalized}_{crane_arch}.tar.gz",
        "archive_type": "tar.gz",
        "binary_name": "crane",
    },
}

_OS_MAP: dict[str, str] = {"linux": "linux", "darwin": "darwin"}
_ARCH_MAP: dict[str, str] = {"amd64": "amd64", "arm64": "arm64"}

_SCRIPT_DIR = Path(__file__).parent.resolve()
_OUTPUT_FILE = (
    _SCRIPT_DIR.parent
    / "src"
    / "xpk"
    / "utils"
    / "dependencies"
    / "binary_dependencies.py"
)


def _get_hash(url: str) -> str:
  with urllib.request.urlopen(url) as response:
    sha256 = hashlib.sha256()
    while chunk := response.read(65536):
      sha256.update(chunk)
    return sha256.hexdigest()


def _get_dep_checksums(dep_info: dict[str, str]) -> dict[str, str]:
  checksums: dict[str, str] = {}
  for os_val, arch_val in product(_OS_MAP.values(), _ARCH_MAP.values()):
    print(f" Calculating checksum for {os_val}_{arch_val}")
    url = dep_info["url_template"].format(
        version=dep_info["version"],
        os=os_val,
        arch=arch_val,
        os_capitalized=os_val.capitalize(),
        crane_arch="x86_64" if arch_val == "amd64" else "arm64",
    )
    checksums[f"{os_val}_{arch_val}"] = _get_hash(url)
  return checksums


def _get_checksums() -> dict[str, dict[str, Any]]:
  checksums: dict[str, dict[str, Any]] = {}
  for dep_name, dep_info in _DEPENDENCIES.items():
    print(f"Updating dependency {dep_name}...")
    checksums[dep_name] = {
        "version": dep_info["version"],
        "archive_type": dep_info["archive_type"],
        "binary_name": dep_info["binary_name"],
        "url_template": dep_info["url_template"],
        "checksums": _get_dep_checksums(dep_info),
    }
  return checksums


def _store_checksums(checksums: dict[str, dict[str, Any]]) -> None:
  _OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

  with open(_OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write(f'"""{_COPYRIGHT_STRING}"""\n')
    f.write(
        "# This file is generated by tools/update_dependencies.py. DO NOT"
        " EDIT.\n"
    )
    f.write("import dataclasses\n")
    f.write("import enum\n\n")
    f.write("@dataclasses.dataclass(frozen=True)\n")
    f.write("class BinaryDependency:\n")
    f.write("    archive_type: str\n")
    f.write("    binary_name: str\n")
    f.write("    checksums: dict[str, str]\n")
    f.write("    url_template: str\n")
    f.write("    version: str\n\n")
    f.write("class BinaryDependencies(enum.Enum):\n")
    for dep_name, dep_data in checksums.items():
      enum_name = dep_name.upper().replace("-", "_")
      f.write(f"    {enum_name} = BinaryDependency(\n")
      f.write(f"        archive_type={repr(dep_data['archive_type'])},\n")
      f.write(f"        binary_name={repr(dep_data['binary_name'])},\n")
      checksums_str = pprint.pformat(dep_data["checksums"], indent=12)
      f.write(f"        checksums={checksums_str},\n")
      f.write(f"        url_template={repr(dep_data['url_template'])},\n")
      f.write(f"        version={repr(dep_data['version'])},\n")
      f.write("    )\n")
  print(f"Checksums written to {_OUTPUT_FILE}")


def _format_code() -> None:
  try:
    subprocess.run(["pyink", str(_OUTPUT_FILE)], check=True)
    print("Formatted with pyink.")
  except FileNotFoundError:
    print("pyink not found, skipping formatting.")
  except subprocess.CalledProcessError as e:
    print(f"pyink formatting failed: {e}")


def generate_checksums() -> None:
  checksums = _get_checksums()
  _store_checksums(checksums)
  _format_code()


if __name__ == "__main__":
  generate_checksums()
