#!/usr/bin/env python3

"""
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import urllib.request
import hashlib
import pprint
import subprocess
from pathlib import Path
from typing import Any

KUBECTL_VERSION: str = "v1.30.0"
KUEUE_VERSION: str = "v0.15.2"
CRANE_VERSION: str = "v0.20.7"

COPYRIGHT_STRING = """
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

DEPENDENCIES: dict[str, dict[str, str]] = {
    "kubectl": {
        "version": KUBECTL_VERSION,
        "url_template": (
            "https://dl.k8s.io/release/{version}/bin/{os}/{arch}/kubectl"
        ),
        "archive_type": "binary",
        "binary_name": "kubectl",
    },
    "kubectl-kueue": {
        "version": KUEUE_VERSION,
        "url_template": "https://github.com/kubernetes-sigs/kueue/releases/download/{version}/kubectl-kueue-{os}-{arch}",
        "archive_type": "binary",
        "binary_name": "kubectl-kueue",
    },
    "crane": {
        "version": CRANE_VERSION,
        "url_template": "https://github.com/google/go-containerregistry/releases/download/{version}/go-containerregistry_{os_capitalized}_{crane_arch}.tar.gz",
        "archive_type": "tar.gz",
        "binary_name": "crane",
    },
}

OS_MAP: dict[str, str] = {"linux": "linux", "darwin": "darwin"}
ARCH_MAP: dict[str, str] = {"amd64": "amd64", "arm64": "arm64"}

SCRIPT_DIR = Path(__file__).parent.resolve()
OUTPUT_FILE = (
    SCRIPT_DIR.parent
    / "src"
    / "xpk"
    / "utils"
    / "dependencies"
    / "checksums.py"
)


def get_hash(url: str) -> str | None:
  with urllib.request.urlopen(url) as response:
    sha256 = hashlib.sha256()
    while chunk := response.read(65536):
      sha256.update(chunk)
    return sha256.hexdigest()


def generate_checksums() -> None:
  checksums: dict[str, dict[str, Any]] = {}
  for dep_name, dep_info in DEPENDENCIES.items():
    print(f"Updating dependency {dep_name}...")
    checksums[dep_name] = {
        "version": dep_info["version"],
        "archive_type": dep_info["archive_type"],
        "binary_name": dep_info["binary_name"],
        "url_template": dep_info["url_template"],
        "checksums": {},
    }
    for os_val in OS_MAP.values():
      for arch_val in ARCH_MAP.values():
        print(f" Calculating checksum for {os_val}_{arch_val}")
        crane_arch = "x86_64" if arch_val == "amd64" else "arm64"
        url = dep_info["url_template"].format(
            version=dep_info["version"],
            os=os_val,
            arch=arch_val,
            os_capitalized=os_val.capitalize(),
            crane_arch=crane_arch,
        )
        checksums[dep_name]["checksums"][f"{os_val}_{arch_val}"] = get_hash(url)

  OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

  with open(OUTPUT_FILE, "w") as f:
    f.write(f'"""{COPYRIGHT_STRING}"""\n')
    f.write(
        "# This file is generated by tools/update_dependencies.py. DO NOT"
        " EDIT.\n"
    )
    f.write("from typing import Any\n\n")
    f.write("DEPENDENCIES: dict[str, dict[str, Any]] = ")
    f.write(pprint.pformat(checksums, indent=4))
    f.write("\n")
  print(f"Checksums written to {OUTPUT_FILE}")

  try:
    subprocess.run(["pyink", str(OUTPUT_FILE)], check=True)
    print("Formatted with pyink.")
  except FileNotFoundError:
    print("pyink not found, skipping formatting.")
  except subprocess.CalledProcessError as e:
    print(f"pyink formatting failed: {e}")


if __name__ == "__main__":
  generate_checksums()
