#!/usr/bin/env python3

"""
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import urllib.request
import hashlib
import pprint
import subprocess
import dataclasses
from pathlib import Path
from itertools import product

_KUBECTL_VERSION: str = "v1.35.2"
_KUEUE_VERSION: str = "v0.15.2"
_CRANE_VERSION: str = "v0.21.2"
_GCLUSTER_VERSION: str = "v1.84.0"

_COPYRIGHT_STRING = """
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


@dataclasses.dataclass(frozen=True)
class _DependencyInfo:
  """Represents a dependency to be fetched and checksummed."""

  name: str
  version: str
  url_template: str
  archive_type: str
  binary_name: str
  arch_map: dict[str, str] = dataclasses.field(default_factory=dict)
  os_map: dict[str, str] = dataclasses.field(default_factory=dict)


_DEPENDENCIES: list[_DependencyInfo] = [
    _DependencyInfo(
        name="kubectl",
        version=_KUBECTL_VERSION,
        url_template=(
            "https://dl.k8s.io/release/{version}/bin/{os}/{arch}/kubectl"
        ),
        archive_type="binary",
        binary_name="kubectl",
    ),
    _DependencyInfo(
        name="kubectl-kueue",
        version=_KUEUE_VERSION,
        url_template="https://github.com/kubernetes-sigs/kueue/releases/download/{version}/kubectl-kueue-{os}-{arch}",
        archive_type="binary",
        binary_name="kubectl-kueue",
    ),
    _DependencyInfo(
        name="crane",
        version=_CRANE_VERSION,
        url_template="https://github.com/google/go-containerregistry/releases/download/{version}/go-containerregistry_{os}_{arch}.tar.gz",
        archive_type="tar.gz",
        binary_name="crane",
        arch_map={"amd64": "x86_64", "arm64": "arm64"},
        os_map={"linux": "Linux", "darwin": "Darwin"},
    ),
    _DependencyInfo(
        name="gcluster",
        version=_GCLUSTER_VERSION,
        url_template="https://github.com/GoogleCloudPlatform/cluster-toolkit/releases/download/{version}/gcluster_bundle_{os}.zip",
        archive_type="zip",
        binary_name="gcluster",
        os_map={"darwin": "mac"},
    ),
]

_OS_MAP: list[str] = ["darwin", "linux"]
_ARCH_MAP: list[str] = ["amd64", "arm64"]

_SCRIPT_DIR = Path(__file__).parent.resolve()
_OUTPUT_FILE = (
    _SCRIPT_DIR.parent
    / "src"
    / "xpk"
    / "utils"
    / "dependencies"
    / "binary_dependencies.py"
)


def _get_hash(url: str) -> str:
  with urllib.request.urlopen(url) as response:
    sha256 = hashlib.sha256()
    while chunk := response.read(65536):
      sha256.update(chunk)
    return sha256.hexdigest()


def _get_dep_checksums(dep_info: _DependencyInfo) -> dict[str, str]:
  checksums: dict[str, str] = {}
  for os_val, arch_val in product(_OS_MAP, _ARCH_MAP):
    print(f" Calculating checksum for {os_val}_{arch_val}")
    mapped_arch = dep_info.arch_map.get(arch_val, arch_val)
    mapped_os = dep_info.os_map.get(os_val, os_val)
    url = dep_info.url_template.format(
        version=dep_info.version,
        os=mapped_os,
        arch=mapped_arch,
    )
    checksums[f"{os_val}_{arch_val}"] = _get_hash(url)
  return checksums


def _get_checksums() -> list[tuple[_DependencyInfo, dict[str, str]]]:
  results: list[tuple[_DependencyInfo, dict[str, str]]] = []
  for dep_info in _DEPENDENCIES:
    print(f"Updating dependency {dep_info.name}...")
    results.append((dep_info, _get_dep_checksums(dep_info)))
  return results


def _store_checksums(
    checksums: list[tuple[_DependencyInfo, dict[str, str]]],
) -> None:
  _OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

  with open(_OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write(f'"""{_COPYRIGHT_STRING}"""\n')
    f.write(
        "# This file is generated by tools/update_dependencies.py. DO NOT"
        " EDIT.\n"
    )
    f.write("import dataclasses\n")
    f.write("import enum\n\n")
    f.write("@dataclasses.dataclass(frozen=True)\n")
    f.write("class BinaryDependency:\n")
    f.write(
        '    """Represents a binary dependency with its metadata and'
        ' checksums."""\n'
    )
    f.write("    archive_type: str\n")
    f.write("    binary_name: str\n")
    f.write("    checksums: dict[str, str]\n")
    f.write("    url_template: str\n")
    f.write("    version: str\n")
    f.write(
        "    arch_map: dict[str, str] ="
        " dataclasses.field(default_factory=dict)\n"
    )
    f.write(
        "    os_map: dict[str, str] ="
        " dataclasses.field(default_factory=dict)\n\n"
    )
    f.write("class BinaryDependencies(enum.Enum):\n")
    f.write(
        '    """Enum of binary dependencies with their metadata and'
        ' checksums."""\n'
    )
    for dep_info, dep_checksums in checksums:
      enum_name = dep_info.name.upper().replace("-", "_")
      f.write(f"    {enum_name} = BinaryDependency(\n")
      f.write(f"        archive_type={repr(dep_info.archive_type)},\n")
      f.write(f"        binary_name={repr(dep_info.binary_name)},\n")
      checksums_str = pprint.pformat(dep_checksums, indent=12)
      f.write(f"        checksums={checksums_str},\n")
      f.write(f"        url_template={repr(dep_info.url_template)},\n")
      f.write(f"        version={repr(dep_info.version)},\n")
      if dep_info.arch_map:
        arch_map_str = pprint.pformat(dep_info.arch_map, indent=12)
        f.write(f"        arch_map={arch_map_str},\n")
      if dep_info.os_map:
        os_map_str = pprint.pformat(dep_info.os_map, indent=12)
        f.write(f"        os_map={os_map_str},\n")
      f.write("    )\n")
  print(f"Checksums written to {_OUTPUT_FILE}")


def _format_code() -> None:
  try:
    subprocess.run(["pyink", str(_OUTPUT_FILE)], check=True)
    print("Formatted with pyink.")
  except FileNotFoundError:
    print("pyink not found, skipping formatting.")
  except subprocess.CalledProcessError as e:
    print(f"pyink formatting failed: {e}")


def generate_checksums() -> None:
  checksums = _get_checksums()
  _store_checksums(checksums)
  _format_code()


if __name__ == "__main__":
  generate_checksums()
