# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

name: Storage Tests

on:
  workflow_call:
    inputs:
      cluster-name:
        type: string
        required: true
      tpu-type:
        description: 'TPU Type'
        required: false
        default: 'v4-2x2x1'
        type: string
      zone:
        type: string
        required: true
      run-id:
        required: true
        type: string

jobs:
  fuse-attach-tests:
    uses: ./.github/workflows/reusable_storage_create.yaml
    concurrency: # We support one build or nightly test to run at a time currently.
      group: fuse-tests-${{inputs.run-id}}
      cancel-in-progress: true
    with:
      cluster-name: ${{inputs.cluster-name}}
      tpu-type: ${{inputs.tpu-type}}
      zone: ${{inputs.zone}}
      storage-type: 'gcsfuse'
      storage-command: 'attach'
      storage-name: fuse-test-${{inputs.run-id}}
    secrets:
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}
      BUCKET_NAME: ${{secrets.BUCKET_NAME}}

  fuse-detach-tests:
    if: always()
    needs: [fuse-attach-tests]
    uses: ./.github/workflows/reusable_storage_delete.yaml
    concurrency: # We support one build or nightly test to run at a time currently.
      group: fuse-tests-${{inputs.run-id}}
    with:
      cluster-name: ${{inputs.cluster-name}}
      zone: ${{inputs.zone}}
      storage-type: 'gcsfuse'
      storage-command: 'detach'
      storage-name: fuse-test-${{inputs.run-id}}
    secrets:
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}

  filestore-create-tests:
    needs: [fuse-attach-tests]
    uses: ./.github/workflows/reusable_storage_create.yaml
    concurrency: # We support one build or nightly test to run at a time currently.
      group: filestore-tests-${{inputs.run-id}}
      cancel-in-progress: true
    with:
      cluster-name: ${{inputs.cluster-name}}
      tpu-type: ${{inputs.tpu-type}}
      zone: ${{inputs.zone}}
      storage-type: 'gcpfilestore'
      storage-command: 'create'
      storage-name: gcpfilestore-test-${{inputs.run-id}}
    secrets:
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}
      BUCKET_NAME: ${{secrets.BUCKET_NAME}}

  filestore-detach-tests:
    needs: [filestore-create-tests]
    uses: ./.github/workflows/reusable_storage_delete.yaml
    concurrency: # We support one build or nightly test to run at a time currently.
      group: filestore-tests-${{inputs.run-id}}
    with:
      cluster-name: ${{inputs.cluster-name}}
      zone: ${{inputs.zone}}
      storage-type: 'gcpfilestore'
      storage-command: 'detach'
      storage-name: 'gcpfilestore-test-${{inputs.run-id}}'
    secrets:
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}

  filestore-attach-tests:
    needs: [filestore-detach-tests]
    uses: ./.github/workflows/reusable_storage_create.yaml
    concurrency: # We support one build or nightly test to run at a time currently.
      group: filestore-tests-${{inputs.run-id}}
      cancel-in-progress: true
    with:
      cluster-name: ${{inputs.cluster-name}}
      tpu-type: ${{inputs.tpu-type}}
      zone: ${{inputs.zone}}
      storage-type: 'gcpfilestore'
      storage-command: 'attach'
      storage-name: gcpfilestore-test-${{inputs.run-id}}
    secrets:
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}
      BUCKET_NAME: ${{secrets.BUCKET_NAME}}

  filestore-delete-tests:
    if: always()
    needs: [filestore-create-tests, filestore-attach-tests]
    uses: ./.github/workflows/reusable_storage_delete.yaml
    concurrency: # We support one build or nightly test to run at a time currently.
      group: filestore-tests-${{inputs.run-id}}
    with:
      cluster-name: ${{inputs.cluster-name}}
      zone: ${{inputs.zone}}
      storage-type: 'gcpfilestore'
      storage-command: 'delete'
      storage-name: gcpfilestore-test-${{inputs.run-id}}
    secrets:
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}

