
on:
  workflow_call:
    inputs:
      group-name:
        required: true
        type: string

jobs:
  run-unit-tests:
    runs-on: [ubuntu-22.04]
    concurrency: # We support one build or nightly test to run at a time currently.
      group: ${{inputs.group-name}}
      cancel-in-progress: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run : make install-dev
    - name: Run unit tests
      run: make run-unittests